export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP FAILURE";

export const FORGOT_REQUEST = "FORGOT_REQUEST";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAILURE = "FORGOT_FAILURE";

export const GETDATA_REQUEST = "GETDATA_REQUEST";
export const GETDATA_SUCCESS = "GETDATA_SUCCESS";
export const GETDATA_FAILURE = "GETDATA_FAILURE";

export const ADDJOB_REQUEST = "ADDJOB_REQUEST";
export const ADDJOB_SUCCESS = "ADDJOB_SUCCESS";
export const ADDJOB_FAILURE = "ADDJOB_FAILURE";

export const ADMIN = "ADMIN";
export const COMPANY = "COMPANY";
export const STUDENT = "STUDENT";
