export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP FAILURE";

export const FORGOT_REQUEST = "FORGOT_REQUEST";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAILURE = "FORGOT_FAILURE";

export const GETDATA_REQUEST = "GETDATA_REQUEST";
export const GETDATA_SUCCESS = "GETDATA_SUCCESS";
export const GETDATA_FAILURE = "GETDATA_FAILURE";

export const ADDJOB_REQUEST = "ADDJOB_REQUEST";
export const ADDJOB_SUCCESS = "ADDJOB_SUCCESS";
export const ADDJOB_FAILURE = "ADDJOB_FAILURE";

export const MYJOB_REQUEST = "MYJOB_REQUEST";
export const MYJOB_SUCCESS = "MYJOB_SUCCESS";
export const MYJOB_FAILURE = "MYJOB_FAILURE";

export const STUDENTJOB_REQUEST = "STUDENTJOB_REQUEST";
export const STUDENTJOB_SUCCESS = "STUDENTJOB_SUCCESS";
export const STUDENTJOB_FAILURE = "STUDENTJOB_FAILURE";

export const DELETESTUDENTJOB_REQUEST = "DELETESTUDENTJOB_REQUEST";
export const DELETESTUDENTJOB_SUCCESS = "DELETESTUDENTJOB_SUCCESS";
export const DELETESTUDENTJOB_FAILURE = "DELETESTUDENTJOB_FAILURE";

export const DELETECOMPANYJOB_REQUEST = "DELETECOMPANYJOB_REQUEST";
export const DELETECOMPANYJOB_SUCCESS = "DELETECOMPANYJOB_SUCCESS";
export const DELETECOMPANYJOB_FAILURE = "DELETECOMPANYJOB_FAILURE";

export const GETALLUSERS_REQUEST = "GETALLUSERS_REQUEST";
export const GETALLUSERS_SUCCESS = "GETALLUSERS_SUCCESS";
export const GETALLUSERS_FAILURE = "GETALLUSERS_FAILURE";

export const BLOCKUSER_REQUEST = "BLOCKUSER_REQUEST";
export const BLOCKUSER_SUCCESS = "BLOCKUSER_SUCCESS";
export const BLOCKUSER_FAILURE = "BLOCKUSER_FAILURE";

export const ALLJOBS_REQUEST = "ALLJOBS_REQUEST";
export const ALLJOBS_SUCCESS = "ALLJOBS_SUCCESS";
export const ALLJOBS_FAILURE = "ALLJOBS_FAILURE";

export const VERIFYUSER_REQUEST = "VERIFYUSER_REQUEST";
export const VERIFYUSER_SUCCESS = "VERIFYUSER_SUCCESS";
export const VERIFYUSER_FAILURE = "VERIFYUSER_FAILURE";

export const ADMIN = "ADMIN";
export const COMPANY = "COMPANY";
export const STUDENT = "STUDENT";
